server:
  port: 10011

spring:
  application:
    name: file-system-server
  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
