server:
  port: 10010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456


swagger:
  title: 文件系统RestApi
  basePackage:
  description:
  version: v0.0.1

cos:
  secretId: AKIDgBTXMvbHApFQM3lkjTzHLAj14rOfGRyG
  secretKey: C9sNdeQxEF0VkjgNo1yf8NN7c5IK7i4B
  bucketName: demo-file-system-1256240650

